'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      'Items',
      [
        {
          price: 45.5,
          image: "https://ae04.alicdn.com/kf/Sd2f53935fdf044aebd546891c2432c63r.jpg",
          title: "Women's long flash evening dress, asymmetric, off shoulder, sleeveless, mop, prom dress",
          size:'S',
          color:'green',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          price: 18.14,
          image: "https://ae01.alicdn.com/kf/S2fe0f30d447b4079ac36ea5ba7ff0391U.jpg",
          title: "Party Dress Plus Size Ladies Midi Sequin Mesh Long Sleeve Lace Elegant Bodycon XL-4XL 5XL Evening Dresses For Women Summer 2022",
          size:'XL',
          color:'red',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          price: 7.18,
          image: "https://ae01.alicdn.com/kf/S5877c19c91574406bf295d64860e99dbL.jpg",
          title: "Large Plus Size Mini Dress Women's 2022 Summer Autumn Sleeveless V Neck Bodycon 4XL Sexy Elegant Cocktail Evening Party Dresses",
          size:'XXL',
          color:'dark blue',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          price: 5.71,
          image: "https://ae04.alicdn.com/kf/S6280a70c0f0b4309801471307c0c2cben.jpg",
          title: "Women's A-Line Dress Fashion Floral Dot 3D Print Knee Length Dress Blue Sleeveless Spring Summer Casual Everyday Dress 2022",
          size:'S',
          color:'light blue',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          price: 15.1,
          image: "https://ae04.alicdn.com/kf/Sce0543b890074127bfce5a941180724a0.jpg",
          title: "Elegant Dresses for Women Diagonal Collar Summer Sexy Satin Single Sleeve Pleated Solid Color Irregular Skirt Black Party Dress",
          size:'L',
          color:'beige',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          price: 10.46,
          image: "https://ae04.alicdn.com/kf/S3621a324e13a44a3a0259e995c44792bF.jpg",
          title: "20 Colors Summer Long Dress 2022 Loose Summer Clothes for Women Everyday Dresses Casual O-Neck Elegant Sleeveless Women Dress",
          size:'XS',
          color:'blue & black',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          price: 8.78,
          image: "https://ae04.alicdn.com/kf/S9ccd525537914fce91ac8580a401d589T.jpg",
          title: "Large Plus Size Mini Dress Women's 2022 Summer Autumn Sleeveless V Neck Bodycon 4XL Sexy Elegant Cocktail Evening Party Dresses",
          size:'M',
          color:'multicolored',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          price: 5.71,
          image: "https://ae04.alicdn.com/kf/S73a6a39f863e45eba86f64f47ebb7165V.jpg",
          title: "Women's A-Line Dress Sleeveless Spring Summer Casual Everyday Dress 2022 Botanical 3D Print Knee Length Dress White Purple Blue",
          size:'L',
          color:'black',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          price: 5.71,
          image: "https://ae04.alicdn.com/kf/S8f6123cc28354674a6bfeb6068520e0d6.jpg",
          title: "Women's A-Line Geometric 3D Print Dress Sleeveless Spring Summer Casual Everyday Dress 2022 Patchwork Print Knee Length Dress",
          size:'S',
          color:'pink & white',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          price: 10.61,
          image: "https://ae04.alicdn.com/kf/HTB12lZIXKbviK0jSZFNq6yApXXaT.jpg",
          title: "Polka Dot Dress Women Vintage Swing Halter Belt 50s 60s Rockabilly Prom Party Dresses Retro Feminino Vestidos",
          size:'XXL',
          color:'polka dot',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
         {
          price: 13.65,
          image: "https://ae04.alicdn.com/kf/S23eafec15fe947819556c2efcd161fc13.jpg",
          title: "Summer Beach Dress Woman Dresses Plus Size Women Floral Sunflower Dress print Ladies Backless Party Dress Female vestidos",
          size:'M',
          color:'dark green',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          price: 22.69,
          image: "https://ae04.alicdn.com/kf/S191dc5f1b15b41b492f6b281e91fe436X.jpg",
          title: "Large Plus Size Mini Dress Women's 2022 Summer Autumn Sleeveless V Neck Bodycon 4XL Sexy Elegant Cocktail Evening Party Dresses",
          size:'XL',
          color:'beige',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          price: 31.91,
          image: "https://ae04.alicdn.com/kf/H0d0bc5b946264c5f861efefeb7556b80E.jpg",
          title: "Women Pink Dress Summer Vintage Elegant Slim European Romance Blue Dress Retro Lace Sexy Slash Neck Casual Everyday Midi Dress",
          size:'M',
          color:'blue',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          price: 39.32,
          image: "https://ae04.alicdn.com/kf/H6475e8aa2af144dea8d3e69a2493c229I.jpg",
          title: "VIMLY Floral Dresses For Women Fashion High Waist Elastic Pleated Dress Vintage Office Lady Maxi Dress Female Vestidos F6806",
          size:'XXL',
          color:'black & white',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          price: 14.96,
          image: "https://ae04.alicdn.com/kf/S3cb00f807642468e882adf120210e775f.jpg",
          title: "Sexy High Split V-neck Maxi Dress for Women Short Sleeve Single Breasted Beach Sundress 2022 Summer New Partywear Vestidos",
          size:'XS',
          color:'white',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          price: 16.07,
          image: "https://ae04.alicdn.com/kf/S619ecf47eecb46ffadc3921a6be7dabb6.jpg",
          title: "Elegant Pleated Dress Women Fashion Butterfly Sleeve O-neck Sashes Office Ladies Midi Dress 2022 Summer Casual Party Dresses",
          size:'L',
          color:'green',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          price: 5.71,
          image: "https://ae04.alicdn.com/kf/Sfcea777062a64b9c84b0359259743cbaV.jpg",
          title: "Ladies Dress Red Black Sleeveless Geometric Print Shift Skirt Spring Summer Casual Fashion Everyday Top 2022 Knee Length Dress",
          size:'XL',
          color:'multicolored',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          price: 14.42,
          image: "https://ae04.alicdn.com/kf/S5f9ce36e9aab43288991f42f3099b450G.jpg",
          title: "ZANZEA Summer Fashion Women Dress Solid Short Sleeve V-Neck Cotton Button Vestido Elegant Casual Oversized Midi Shirtdress 2022",
          size:'XXL',
          color:'blue',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          price: 14.77,
          image: "https://ae04.alicdn.com/kf/S45c1d50d648a47e9b2837604c45ce0725.jpg",
          title: "2022 New Women Summer Long Dress Draw String Slim Print Vintage Dress Women High Quality Short Sleeve Casual Everyday Dress",
          size:'M',
          color:'multicolored',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          price: 14.42,
          image: "https://ae04.alicdn.com/kf/S61a8433084cf4242a33dadb2e2f034caP.jpg",
          title: "Sexy tropical print short-sleeved robe casual everyday elegant lady floral dress",
          size:'XL',
          color:'multicolored',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 1,
          createdAt: new Date(),
          updatedAt: new Date()
        },
          //HOODIES
          {
            price: 10.06,
            image: "https://ae04.alicdn.com/kf/S6624c1d33f2c48a58d49af6c92e1f8b2y.jpg",
            title: "2022Japan Anime Chainsaw Men and womenHoodies Gothic Cartoon Double-sided Print Oversized Streetwear Long Sleeve Sweatshirts",
            size:'L',
            color:'black',
            brand: null,
            processor: null,
            display: null,
            gender: null,
            style: null,
            category_id: 2,
            createdAt: new Date(),
            updatedAt: new Date()
          },
          {
            price: 8.88,
            image: "https://ae04.alicdn.com/kf/S6f0a207bcceb4431b4c821175ad1c70cC.jpg",
            title: "New Men WomenHoodies Kpop Stray Kids Print Sweatshirts  Fashion Black Pullover  Sweatshirt Unisex Harajuku Oversized Hoodie Top",
            size:'M',
            color:'black',
            brand: null,
            processor: null,
            display: null,
            gender: null,
            style: null,
            category_id: 2,
            createdAt: new Date(),
            updatedAt: new Date()
          },
          {
            price: 19.44,
            image: "https://ae04.alicdn.com/kf/S7da7a60597d8433ea6abbe9869e05ba99.jpg",
            title: "Y2k Clothes Autumn and Winter 2022 Men and WomenHoodies Sweatshirts Hip-Hop Streetwears Casual Zip-Up Hooded Sweatshirt Clothing",
            size:'XL',
            color:'white',
            brand: null,
            processor: null,
            display: null,
            gender: null,
            style: null,
            category_id: 2,
            createdAt: new Date(),
            updatedAt: new Date()
          },
          {
            price: 11.12,
            image: "https://ae04.alicdn.com/kf/S72aa65721b62406c83b09b0d0d3603127.jpg",
            title: "Funny Japanese Anime Demon Slayer Print Men and WomenHoodies Sweatshirts Hoodie Patchwork Thin Clothing Hip Hop Streetwear Tops",
            size:'XL',
            color:'black & white',
            brand: null,
            processor: null,
            display: null,
            gender: null,
            style: null,
            category_id: 2,
            createdAt: new Date(),
            updatedAt: new Date()
          },
           {
          price: 7.05,
          image: "https://ae04.alicdn.com/kf/S1e62a70e4046418daa1cb20961a3e684A.jpg",
          title: "Korean Fashion WomenHoodies Hip Hop Harajuku Men Streetwear Sweatshirts 2022 New Autumn And Winter Clothes With Pockets Hoodie",
          size:'S',
          color:'darl red',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 2,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          price: 15.65,
          image: "https://ae04.alicdn.com/kf/Sc2371097aa674fe4a144050c19d13dd2X.jpg",
          title: "Anime Rurouni Kenshin Hoodies Manga Kenshin and Kaoru Winter Warm WomenHoodie Spring/Autumn Unisex Sweatshirt Harajuku Sudaderas",
          size:'M',
          color:'beige',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 2,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          price: 7.42,
          image: "https://ae01.alicdn.com/kf/S801a59bb1b4e443baccf00d7e8cfa743v.jpg",
          title: "2022 Summer Korean O-neck Knitted Sweaters Women Thin Cardigan Fashion Casual Slim fit Tops Femme Single-breasted Shirt",
          size:'s',
          color:'green',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 2,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          price: 14.24,
          image: "https://ae01.alicdn.com/kf/Hf97d3fa6e31a458e810a7371c9c338e1X.jpg",
          title: "Women Leopard Sweater Leopard Patch Faux Fur Cardigan Hooded Winter Coat Plus Size 5XL Teddy Sweaters Ladies Oversized Tops",
          size:'L',
          color:'leopard',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 2,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          price: 14.42,
          image: "https://ae01.alicdn.com/kf/Sa24d07521fab4758a8340d7bea329430o.jpg",
          title: "Retro Lambs Wool Women Solid Color Pockets Design Teddy Jacket Baggy Long Sleeve V-neck Knit Cardigan Sweater Simple Basic Chic",
          size:'S',
          color:'multicolored',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 2,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          price: 14.42,
          image: "https://ae01.alicdn.com/kf/Sfbd874ee15a84c4e9cf7b5d7a020f5465.jpg",
          title: "Autumn and winter style hooded coat imitation fur lady cardigan women Fur Jacket Female Plush Overcoat Pocket Teddy Bear Outwear",
          size:'L',
          color:'gray',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 2,
          createdAt: new Date(),
          updatedAt: new Date()
        },

        //SHIRTS

        {
          price: 12.61,
          image: "https://ae01.alicdn.com/kf/H26e69e211b6c42c196eb29506ec1ca12j.jpg",
          title: "Spring 2022 Cotton 100% Long Sleeve White T-Shirts Women Loose Printing Slim Autumn Tee Ladies Soft Coffee Split Hem O-Neck Tops",
          size:'S',
          color:'white',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 3,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          price: 9.56,
          image: "https://ae01.alicdn.com/kf/Sd15c7433f3c6476da62e2edb9706325fB.jpg",
          title: "Women T-shirt Summer 100% Cotton Short Sleeve Female Graphic Fashion T Shirt Black Cat Print Ladies Regular Round Neck Tees Tops",
          size:'M',
          color:'yellow',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 3,
          createdAt: new Date(),
          updatedAt: new Date()
        }, {
          price: 7.32,
          image: "https://ae01.alicdn.com/kf/Hbe2a98ea9da545b2b3ae53ad3e2f20deY.jpg",
          title: "FLC Funny Corgi T Shirt Women Clothes Kawaii Dog Graphic Short Sleeve Tee Unisex Men Tops Harajuku Casual Corgi Female T Shirt",
          size:'L',
          color:'black',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 3,
          createdAt: new Date(),
          updatedAt: new Date()
        }, {
          price: 25.99,
          image: "https://ae01.alicdn.com/kf/S39b5e93db530424cb92f4b7661a82a03W.jpg",
          title: "2022new t shirt womenshirt femme tshirt women t-shirt summer t shirts Women Clothing Broadcloth  Casual 2021",
          size:'XL',
          color:'white',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 3,
          createdAt: new Date(),
          updatedAt: new Date()
        }, {
          price: 28.99,
          image: "https://ae01.alicdn.com/kf/Sd60194ee9e6749388e9fd10f20ce200fN.jpg",
          title: "Women Short Sleeve O Neck Loose Tshirt 2021 WomenShirt Cotton",
          size:'XXL',
          color:'multicolored',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 3,
          createdAt: new Date(),
          updatedAt: new Date()
        }, {
          price: 21.99,
          image: "https://ae01.alicdn.com/kf/S4c2b7d0e4a0949eb8f59690a1984717dD.jpg",
          title: "t shirt womenshirt femme tshirt women t-shirt summer t shirts Women Clothing Broadcloth  Casual",
          size:'S',
          color:'green',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 3,
          createdAt: new Date(),
          updatedAt: new Date()
        }, {
          price: 4.02,
          image: "https://ae01.alicdn.com/kf/Sd5420b19f0484392a23de23788747abaU.jpg",
          title: "Gemini File birthday party Tshirt Female Clothing 100%Cotton Womenshirt Short Sleeve Top Tees Harajuku Streetwear Drop Shipping",
          size:'M',
          color:'pink',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 3,
          createdAt: new Date(),
          updatedAt: new Date()
        }, {
          price: 13.88,
          image: "https://ae01.alicdn.com/kf/H2965a30225334ede9375262cfa015cadv.jpg",
          title: "2021 autumnnew Korean version of lace v-neck lace top fashion trumpet sleeve nine-point sleeve lace bottoming officeshirt women",
          size:'L',
          color:'orange',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 3,
          createdAt: new Date(),
          updatedAt: new Date()
        }, {
          price: 8.18,
          image: "https://ae01.alicdn.com/kf/H7414f6c9069943f6987ee9fc69caca485.jpg",
          title: "Ribbed Seamless Women Sports Bra Shockproof Crop Top Gym Shirt Long Sleeve Fitness Yoga Top Running Sport Tops Short Sleev N0240",
          size:'XL',
          color:'white',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 3,
          createdAt: new Date(),
          updatedAt: new Date()
        }, {
          price: 15.97,
          image: "https://ae01.alicdn.com/kf/Sd617e4a3dc354d2aa495ee6148504a47X.jpg",
          title: "Plus Size Tops Rose Turn Down Collar Long Puff Sleeve See Through Organza Polka Dot Blouse Office Lady Evening Party Shirts Top",
          size:'XXL',
          color:'pink',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 3,
          createdAt: new Date(),
          updatedAt: new Date()
        },

        //JEANS
        {
          price: 65.35,
          image: "https://ae01.alicdn.com/kf/S8f871fcbbea14d86b72c24570f43afadC/Black-High-Waist-Jeans-Women-s-2022-Spring-New-All-match-Skinny-Skinny-Stretch-Jeans.jpg_220x220xz.jpg",
          title: "Black High Waist Jeans Women's 2022 Spring New All-match Skinny Skinny Stretch Jeans",
          size:'S',
          color:'black',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 4,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          price: 25.75,
          image: "https://ae01.alicdn.com/kf/Sf5d8e48e161e46248a36776cac09db8dr/2022-Fashion-Versatile-High-Waist-Jeans-Women-s-Skinny-Skinny-Jeans-High-Quality.jpg_220x220xz.jpg",
          title: "2022 Fashion Versatile High Waist Jeans Women's Skinny Skinny Jeans High Quality",
          size:'M',
          color:'gray',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 4,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          price: 11.04,
          image: "https://ae01.alicdn.com/kf/H807d05104ec243da8adb69468cceb05fZ/New-Women-Jeans-2021-Autumn-Elastic-Pencil-Trousers-High-Waist-Ladies-Tight-Clothing-Slim-Fit-Casual.jpg_220x220xz.jpg",
          title: "New Women Jeans 2021 Autumn Elastic Pencil Trousers High Waist Ladies Tight Clothing Slim Fit Casual Skinny Denim Pants Women",
          size:'L',
          color:'blue',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 4,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          price: 15.97,
          image: "https://ae01.alicdn.com/kf/Sf62f5d5e546c46a5b5f383e1e0f45cb3i/Fashion-Casual-Ladies-Denim-Pants-High-Quality-Womens-Skinny-Jeans-Woman.jpg_220x220xz.jpg",
          title: "Fashion Casual Ladies Denim Pants High Quality Womens Skinny Jeans Woman",
          size:'XL',
          color:'dark blue',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 4,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          price: 9.08,
          image: "https://ae01.alicdn.com/kf/S466b8ed9a8004abaa3d1f056422e80ecO/2022-FW-Fashion-Women-s-European-and-American-Style-Straight-Letter-High-Waist-Stretch-Women-s.jpg_220x220xz.jpg",
          title: "2022 FW Fashion Women's European and American Style Straight Letter High Waist Stretch Women's Jeans Pure Cotton High Quality",
          size:'L',
          color:'light blue',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 4,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          price: 22.43,
          image: "https://ae01.alicdn.com/kf/S624532d1cfdd406897fa3c35d3745281E/2022-New-Women-s-Jeans-Ripped-Slim-Fit-Fashion-High-Waist-Streetwear-Vintage-Stretch-Casual-Denim.jpg_Q90.jpg",
          title: "2022 New Women's Jeans Ripped Slim Fit Fashion High Waist Streetwear Vintage Stretch Casual Denim Pants",
          size:'M',
          color:'light blue',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 4,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          price: 21.39,
          image: "https://ae01.alicdn.com/kf/S5b2e9dd7cdbb40b1ae8324b2c60376c8K/Tawaaiw-Streetwear-Blue-Pentagram-High-Waist-Jeans-Y2k-Korean-Style-Hip-Hop-Straight-Denim-Boyfriend-Jeans.jpg_Q90.jpg",
          title: "Tawaaiw Streetwear Blue Pentagram High Waist Jeans Y2k Korean Style Hip Hop Straight Denim Boyfriend Jeans For Women Trousers",
          size:'XL',
          color:'blue',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 4,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          price: 27.55,
          image: "https://ae01.alicdn.com/kf/S17c207ca28dc4dedba0d1f8101c3a2daO/Retro-Five-Pointed-Star-Straight-Women-Jeans-European-and-American-Style-Design-Slim-Fit-Leg-Length.jpg_Q90.jpg",
          title: "Retro Five Pointed Star Straight Women Jeans European and American Style Design Slim Fit Leg Length All Match Pants",
          size:'S',
          color:'blue',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 4,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          price: 20.23,
          image: "https://ae01.alicdn.com/kf/S5559709fc69e471195e4f38d17a74f0au/Jeans-Women-High-Waist-Trousers-Denim-Street-Style-Pants-Trendy-Loose-and-Casual-Versatile-Fashion-Straight.jpg_Q90.jpg",
          title: "Jeans Women High Waist Trousers Denim Street Style Pants Trendy Loose and Casual Versatile Fashion Straight Pants Plus Size",
          size:'XL',
          color:'black',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 4,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          price: 25.87,
          image: "https://ae01.alicdn.com/kf/S37cac086ac8b4ee6a12509b02a8b4e973/Letter-Print-Straight-Loose-Jeans-Womens-Retro-High-Street-Oversize-Casual-Denim-Trousers-Harajuku-Washed-Hip.jpg_Q90.jpg",
          title: "Letter Print Straight Loose Jeans Womens Retro High Street Oversize Casual Denim Trousers Harajuku Washed Hip Hop Jean Pants",
          size:'L',
          color:'black',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 4,
          createdAt: new Date(),
          updatedAt: new Date()
        },
       //SHOES

       {
        price: 32.75,
        image: "https://ae01.alicdn.com/kf/H43c1da813d11420ebc36efc77748f777x/Hot-Brand-New-Glamour-Purple-Women-Mid-Calf-Boots-Office-Lady-Dress-Shoes-Super-High-Spike.jpg_Q90.jpg",
        title: "Hot Brand New Glamour Purple Women Mid Calf Boots Office Lady Dress Shoes Super High Spike Heel Plus Small Big Size 11 32 45 48",
        size:'36',
        color:'purple',
        brand: null,
        processor: null,
        display: null,
        gender: null,
        style: null,
        category_id: 5,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        price: 30.27,
        image: "https://ae01.alicdn.com/kf/Hf3d6cc5a7de94c8c8c67ffebc97d2f76n/Winter-Warm-Women-s-Sweet-Lolita-Bowknot-Boots-Rabbit-Fur-Plush-Booties-Chuncky-Heels-Low-Heel.jpg_Q90.jpg",
        title: "Winter Warm Women's Sweet Lolita Bowknot Boots Rabbit Fur Plush Booties Chuncky Heels Low Heel Knee High Boots Pearl Pendant",
        size:'39',
        color:'pink',
        brand: null,
        processor: null,
        display: null,
        gender: null,
        style: null,
        category_id: 5,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        price: 59.32,
        image: "https://ae01.alicdn.com/kf/S5dedfe1dcebf413899f18a360a04bd97N/Platform-Women-Knee-High-Boots-Fashion-Concise-Casual-Thick-Heels-Round-Toe-Genuine-Leather-Zip-Shoes.jpg_Q90.jpg",
        title: "Platform Women Knee-High Boots Fashion Concise Casual Thick Heels Round Toe Genuine Leather Zip Shoes Woman Autumn Winter",
        size:'40',
        color:'black',
        brand: null,
        processor: null,
        display: null,
        gender: null,
        style: null,
        category_id: 5,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        price: 11.66,
        image: "https://ae01.alicdn.com/kf/Sccce8317df39452dbabf249f640ce0b5s/Snow-Women-Boots-Fur-Ladies-Shoes-Slip-On-Platform-Shoes-Woman-Plus-Size-Ankle-Boots-Waterproof.jpg_Q90.jpg",
        title: "Snow Women Boots Fur Ladies Shoes Slip On Platform Shoes Woman Plus Size Ankle Boots Waterproof Plush Winter Boots Botas Mujer",
        size:'38',
        color:'wine red',
        brand: null,
        processor: null,
        display: null,
        gender: null,
        style: null,
        category_id: 5,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        price: 58.21,
        image: "https://ae01.alicdn.com/kf/S093b140e3ab746a2b6f3eb13c9c807ffS/Moirnc-Dutti-Women-Chelsea-Boots-Women-Black-Leather-Short-Boots-11184850800.jpg_Q90.jpg",
        title: "Moirnc Dutti Women Chelsea Boots Women Black Leather Short Boots",
        size:'39',
        color:'black',
        brand: null,
        processor: null,
        display: null,
        gender: null,
        style: null,
        category_id: 5,
        createdAt: new Date(),
        updatedAt: new Date()
      },
       {
          price: 25.87,
          image: "https://ae01.alicdn.com/kf/S0aa2b2594fd54cd1bf7bacaf080f1ab6Y/2022-Women-Boots-Over-The-Knee-Boots-Sexy-Fashion-Stiletto-Heels-Pointed-Boots-Party-Bar-Pole.jpg_Q90.jpg",
          title: "2022 Women Boots Over The Knee Boots Sexy Fashion Stiletto Heels Pointed Boots Party Bar Pole Dance Bounce Boots PROM Size 34-46",
          size:'40',
          color:'red',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 5,
          createdAt: new Date(),
          updatedAt: new Date()
        },
         {
          price: 8.51,
          image: "https://ae01.alicdn.com/kf/Sce3c222a9b754739b2ad9e7722fa0656r/YISHEN-Women-Rain-Boots-New-Trend-Walking-Casual-Shoes-Waterproof-Ankle-Boots-Thick-Bottom-4-5CM.jpg_Q90.jpg",
          title: "YISHEN Women Rain Boots New Trend Walking Casual Shoes Waterproof Ankle Boots Thick Bottom 4.5CM Jelly Boot Bottes De Pluie",
          size:'35',
          color:'green',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 5,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          price: 15.50,
          image: "https://ae01.alicdn.com/kf/U597d4fb5a1e3487ba347febac319f4969/black-with-white-high-heels-pointed-toe-fashion-women-praty-dress-ankle-boots.jpg_Q90.jpg",
          title: "black with white high heels pointed toe fashion women praty dress ankle boots",
          size:'37',
          color:'black',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 5,
          createdAt: new Date(),
          updatedAt: new Date()
        },
         {
          price: 49.21,
          image: "https://ae01.alicdn.com/kf/S34f9879b7c9e4396a79967d7b40f5b27t/2022-Winter-Boots-Fur-Ladies-Snow-Boots-Real-Sheepskin-Wool-Low-cut-Warm-Fur-Shoes-Man.jpg_Q90.jpg",
          title: "2022 Winter Boots Fur Ladies Snow Boots Real Sheepskin Wool Low-cut Warm Fur Shoes Man and Women Winter Short Boots Super Mini",
          size:'39',
          color:'grey',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 5,
          createdAt: new Date(),
          updatedAt: new Date()
        },
         {
          price: 54.25,
          image: "https://ae01.alicdn.com/kf/Sd291ee8fd6034238924966308b41397dM/2021-New-Winter-Knee-High-Motorcycle-Boots-Fashion-Female-Platform-Shoes-Sexy-Ladies-Black-Brown-White.jpg_Q90.jpg",
          title: "Letter Print Straight Loose Jeans Womens Retro High Street Oversize Casual Denim Trousers Harajuku Washed Hip Hop Jean Pants",
          size:'38',
          color:'white',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 5,
          createdAt: new Date(),
          updatedAt: new Date()
        },

        //SUITS
        {
          price: 25.23,
          image: "https://ae01.alicdn.com/kf/H5c0602c2131049468afef6b9ff04540dz/2021-Men-s-Business-Suit-3-Piece-Plus-Size-Slim-Fit-Solid-Color-Straight-Pants-Men.jpg_Q90.jpg",
          title: "2021 Men's Business Suit 3 Piece Plus Size Slim Fit Solid Color Straight Pants Men Blazer Set Formal Suit Separates for Banquet",
          size:'S',
          color:'black',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 6,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          price: 87.10,
          image: "https://ae01.alicdn.com/kf/Sd70277046e834d3ca9be22ba18723438T/Men-s-High-quality-Suit-Business-Professional-Youth-Office-Worker-Formal-Dress-Wedding-Banquet-Gentleman-Suit.jpg_Q90.jpg",
          title: "Men's High-quality Suit Business Professional Youth Office Worker Formal Dress Wedding Banquet Gentleman Suit Dress Two-piece",
          size:'M',
          color:'navy blue',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 6,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          price: 10.20,
          image: "https://ae01.alicdn.com/kf/Se2aee38a67cb474d9654a1135bee238bG/Men-s-Vests-Tweed-Suit-Business-Clothing-for-Men-Striped-Waistcoat-Punk-Vest-Groomman-Wedding-Brwon.jpg_Q90.jpg",
          title: "Men's Vests Tweed Suit Business Clothing for Men Striped Waistcoat Punk Vest Groomman Wedding Brwon Black Grey Jacket",
          size:'XL',
          color:'grey',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 6,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          price: 65.14,
          image: "https://ae01.alicdn.com/kf/S1b534a8db0594474a06a2a8bcac2b424R/Men-Suit-Groom-Wear-Business-Casual-Party-Suit-For-Men-Slim-Fit-Shawl-Lapel-3-Piece.png",
          title: "Men Suit Groom Wear Business Casual Party Suit For Men Slim Fit Shawl Lapel 3 Piece （Blazer + Vest+ Pants）Costume Homme",
          size:'XXL',
          color:'white',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 6,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          price: 44.20,
          image: "https://ae01.alicdn.com/kf/Sde8d2870e8bb4101a9e78f02a34a83ebD/Sleeveless-Men-s-Suit-Vests-with-Double-Breasted-Slim-Fit-Groomsmen-Waistcoat-for-Wedding-Business-Single.jpg_Q90.jpg",
          title: "Sleeveless Men's Suit Vests with Double Breasted Slim Fit Groomsmen Waistcoat for Wedding Business Single One Piece Male Coat",
          size:'XXXL',
          color:'black',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 6,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          price: 41.20,
          image: "https://ae01.alicdn.com/kf/Seb2e46c0bdae425d8b5683d6bec1d555r/Purple-Mens-Suits-Slim-Fit-Wedding-Groom-Tuxedos-Formal-Banquet-Blazer-Beat-Man-3-Piece-Set.jpg_Q90.jpg",
          title: "Purple Mens Suits Slim Fit Wedding Groom Tuxedos Formal Banquet Blazer Beat Man 3 Piece Set Terno Masculino Jacket Vest Pants",
          size:'M',
          color:'purple',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 6,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          price: 63.32,
          image: "https://ae01.alicdn.com/kf/S68080ce9c6cb4c25b0206bc40bf4c0eco/Men-Business-Casual-Wedding-Party-Three-Pieces-Jacket-Trousers-Waistcoat-Set-Male-Blazer-Coat-Pants-Vest.jpg_Q90.jpg",
          title: "White Mens Suits Slim Fit Wedding Groom Tuxedos Formal Banquet Blazer Beat Man 3 Piece Set Terno Masculino Jacket Vest Pants",
          size:'S',
          color:'white',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 6,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          price: 52.10,
          image: "https://ae01.alicdn.com/kf/S8074d0de7f7344bf9deeda46a43297f49/Male-Suit-Army-Green-Groom-Tuxedos-Party-Suit-Slim-Fit-Business-Casual-Jacket-Sets-3-Piece.png",
          title: "Male Suit Army Green Groom Tuxedos Party Suit Slim Fit Business Casual Jacket Sets 3 Piece （Blazer + Vest + Pants）Costume Homme",
          size:'L',
          color:'green',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 6,
          createdAt: new Date(),
          updatedAt: new Date()
        },

        // JEANS AND PANTS
        {
          price: 10.23,
          image: "https://ae01.alicdn.com/kf/Sdb0fe787471c451fa538a9c2f95310aea/Men-s-Vintage-Light-Blue-Jeans-Autumn-Streetwear-Slim-Fit-Straight-Pants-Casual-Cotton-Scratched-Denim.jpg_Q90.jpg",
          title: "Men's Vintage Light Blue Jeans Autumn Streetwear Slim Fit Straight Pants Casual Cotton Scratched Denim Trousers CP2158",
          size:'32',
          color:'light blue',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 7,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          price: 44.20,
          image: "https://ae01.alicdn.com/kf/S33fdbf14ec7b4f889619abcb2cefb609p/2022-New-Men-s-Stretch-Skinny-Jeans-New-Spring-Fashion-Casual-Cotton-Denim-Slim-Fit-Pants.jpg_Q90.jpg",
          title: "2022 New Men's Stretch Skinny Jeans New Spring Fashion Casual Cotton Denim Slim Fit Pants Male Trouse",
          size:'34',
          color:'sky blue',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 7,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          price: 52.23,
          image: "https://ae01.alicdn.com/kf/H09ad18e8c2324df195d98857aed2016aA/2021-new-men-s-jeans-spring-and-autumn-pants-trendy-casual-trousers.jpg_Q90.jpg",
          title: "2021 new men's jeans spring and autumn pants trendy casual trousers ",
          size:'40',
          color:'black',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 7,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          price: 48.36,
          image: "https://ae01.alicdn.com/kf/Sb51a7714939a4b76bdd2517f93badbb03/2022-Winter-New-Men-s-Warm-Slim-Fit-Jeans-Business-Fashion-Thicken-Denim-Trousers-Fleece-Stretch.jpg_Q90.jpg",
          title: "2022 Winter New Men's Warm Slim Fit Jeans Business Fashion Thicken Denim Trousers Fleece Stretch Brand Pants Black Blue",
          size:'36',
          color:'black',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 7,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          price: 50.10,
          image: "https://ae01.alicdn.com/kf/S21fad5d096b74e91a61eda49b5754b549/2022-New-Jeans-Men-Stretch-Straight-Tube-Slim-Men-Jeans-Casual-Fashion-Versatile-Jeans-High-Quality.jpg_Q90.jpg",
          title: "2022 New Jeans Men Stretch Straight Tube Slim Men Jeans Casual Fashion Versatile Jeans High Quality",
          size:'35',
          color:'black',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 7,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          price: 47.20,
          image: "https://ae01.alicdn.com/kf/S06de1c6a454944c3b8ab4f158faa6245I/2022-New-Men-s-jeans-Winter-Fleece-Jeans-Thick-Warm-Denim-Pants-Men-Streetwear-Black-Joggers.jpg_Q90.jpg",
          title: "2022 New Men's jeans Winter Fleece Jeans Thick Warm Denim Pants Men Streetwear Black Joggers Harem Jean Thermal Trousers",
          size:'32',
          color:'gray',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 7,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          price: 52.32,
          image: "https://ae01.alicdn.com/kf/Sd4b85f1e762e454780247277368673f2E/Spring-Summer-Men-s-Jeans-Cotton-Denim-Hip-Hop-Slack-Bottom-Joggers-Streetwear-Skinny-Blue-Pants.jpg_Q90.jpg",
          title: "Spring Summer Men's Jeans Cotton Denim Hip Hop Slack Bottom Joggers Streetwear Skinny Blue Pants Hombre Harem Trousers Men S-3XL",
          size:'32',
          color:'blue',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 7,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          price: 41.50,
          image: "https://ae01.alicdn.com/kf/Sf7c9804664c64e528ba0c7dc78cd5405N/2022-New-Hip-Hop-Harem-Jeans-Pants-Men-Loose-Joggers-Denim-Casual-Sweatpants-Korea-Ankle-Length.jpg_Q90.jpg",
          title: "2022 New Hip Hop Harem Jeans Pants Men Loose Joggers Denim Casual Sweatpants Korea Ankle Length Trousers Streetwear Male Clothes",
          size:'36',
          color:'gray',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 7,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          price: 70.50,
          image: "https://ae01.alicdn.com/kf/S3d3ffdad2dd8456ea2c3c86556394323w/2022-New-Winter-and-Autumn-Mens-Casual-Jeans-Fashion-Slim-Cotton-Denim-Pants-Skinny-Jeans.jpg_Q90.jpg",
          title: "2022 New Winter and Autumn Mens Casual Jeans Fashion Slim Cotton Denim Pants Skinny Jeans",
          size:'32',
          color:'blue',
          brand: null,
          processor: null,
          display: null,
          gender: null,
          style: null,
          category_id: 7,
          createdAt: new Date(),
          updatedAt: new Date()
        },
       // SWEATERS
       {
        price: 23.7,
        image: "https://ae01.alicdn.com/kf/S6ba2d8a0bf5e49d68f1092847f3e50e3y/2022-New-Autumn-Winter-Casual-Sweater-Men-Loose-Harajuku-Style-Round-Neck-Long-Sleeve-Mens-Fashion.jpg_Q90.jpg",
        title: "2022 New Autumn Winter Casual Sweater Men Loose Harajuku Style Round Neck Long Sleeve Mens Fashion Pullovers Trendy Sweaters",
        size:'XL',
        color:'black & white',
        brand: null,
        processor: null,
        display: null,
        gender: null,
        style: null,
        category_id: 8,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        price: 12.5,
        image: "https://ae01.alicdn.com/kf/S74de5ffbf2d94c92ba4b442ab3faa420H/Winter-Men-s-Fleece-Thicker-Sweater-Half-Zipper-Turtleneck-Warm-Pullover-Quality-Male-Slim-Knitted-Wool.jpeg_Q90.jpeg",
        title: "Winter Men's Fleece Thicker Sweater Half Zipper Turtleneck Warm Pullover Quality Male Slim Knitted Wool Sweaters for Spring",
        size:'M',
        color:'light grey',
        brand: null,
        processor: null,
        display: null,
        gender: null,
        style: null,
        category_id: 8,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        price: 40.5,
        image: "https://ae01.alicdn.com/kf/S8f099d3f1d4b4172b52dccada25300dap/2022-Personalized-men-sweater-regular-round-neck-customize-advertising-sweater-A1371-button-up-blue-wine-red.jpg_Q90.jpg",
        title: "2022 Personalized men sweater regular round neck customize advertising sweater A1371 button up blue wine red grey cotton",
        size:'XL',
        color:'beige',
        brand: null,
        processor: null,
        display: null,
        gender: null,
        style: null,
        category_id: 8,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        price: 11.20,
        image: "https://ae01.alicdn.com/kf/S32410a2c8460489f96a7e8920fcb17a8e/Autumn-Winter-Men-s-Turtleneck-Sweater-Men-s-Knitting-Pullovers-Rollneck-Knitted-Sweater-Warm-Men-Jumper.jpg_Q90.jpg",
        title: "Autumn Winter Men's Turtleneck Sweater Men's Knitting Pullovers Rollneck Knitted Sweater Warm Men Jumper Slim Fit Casual Sweater",
        size:'L',
        color:'brown',
        brand: null,
        processor: null,
        display: null,
        gender: null,
        style: null,
        category_id: 8,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        price: 23.30,
        image: "https://ae01.alicdn.com/kf/S4f824d4f3a0341fba27b1c8f5974cecfO/2022-Personalized-men-sweater-regular-round-neck-customize-advertising-sweater-A1364-open-collar-grey-black-acrylic.jpg_Q90.jpg",
        title: "2022 Personalized men sweater regular round neck customize advertising sweater A1364 open collar grey black acrylic",
        size:'M',
        color:'grey',
        brand: null,
        processor: null,
        display: null,
        gender: null,
        style: null,
        category_id: 8,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        price: 41.20,
        image: "https://ae01.alicdn.com/kf/Sf6fa9f0f6d32411890eddd1eed2a730ds/2022-Autumn-and-Winter-New-Men-s-Turtleneck-Sweater-Male-Korean-Version-Casual-All-match-Knitted.jpg_Q90.jpg",
        title: "2022 Autumn and Winter New Men's Turtleneck Sweater Male Korean Version Casual All-match Knitted Bottoming Shirt",
        size:'XXL',
        color:'grey',
        brand: null,
        processor: null,
        display: null,
        gender: null,
        style: null,
        category_id: 8,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        price: 20.40,
        image: "https://ae01.alicdn.com/kf/S236311deb5bb4660ae6719b9ba169f4cI/Turtleneck-American-sweater-for-men-and-women-knitwear-Winter-men-sweater-for-thick-style-trend-loose.jpg_Q90.jpg",
        title: "Turtleneck American sweater for men and women knitwear Winter men sweater for thick style trend loose slouchy outerwear sweater",
        size:'S',
        color:'multicolored',
        brand: null,
        processor: null,
        display: null,
        gender: null,
        style: null,
        category_id: 8,
        createdAt: new Date(),
        updatedAt: new Date()
      },

      //JACKETS
      {
        price: 50.47,
        image: "https://ae01.alicdn.com/kf/Hbffc9e262e98406699dc60967c05b0f4M/Winter-Jacket-Men-Thicken-Jacket-With-Fur-Lined-Warm-Parka-Cold-Weather-Clothes-Men-Outdoor-Jacket.jpg_Q90.jpg",
        title: "Winter Jacket Men Thicken Jacket With Fur Lined Warm Parka Cold Weather Clothes Men Outdoor Jacket Windproof Plus Size 8XL",
        size:'XL',
        color:'khaki',
        brand: null,
        processor: null,
        display: null,
        gender: null,
        style: null,
        category_id: 9,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        price: 20.40,
        image: "https://ae01.alicdn.com/kf/S5af3b46e9fa144aeb92e5bc0a0b4ca09f/Men-Outdoor-Windproof-Jacket-Windbreaker-Coat-Hiking-Rain-Camping-Fishing-Tactical-Male-Clothing-Breathable-Jackets-Plus.jpg_Q90.jpg",
        title: "Men Outdoor Windproof Jacket Windbreaker Coat Hiking Rain Camping Fishing Tactical Male Clothing Breathable Jackets Plus Size",
        size:'M',
        color:'beige',
        brand: null,
        processor: null,
        display: null,
        gender: null,
        style: null,
        category_id: 9,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        price: 35.50,
        image: "https://ae01.alicdn.com/kf/S5b2bbda272924589ab0c5c57a396b558q/2022-New-Spring-and-Autumn-Jacket-Men-Plus-Size-Hooded-Outerwear-Trendy-Street-College-Style-Clothing.jpg_Q90.jpg",
        title: "2022 New Spring and Autumn Jacket Men Plus Size Hooded Outerwear Trendy Street College Style Clothing Men's Hoodie Zip Jackets",
        size:'M',
        color:'multicolored',
        brand: null,
        processor: null,
        display: null,
        gender: null,
        style: null,
        category_id: 9,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        price: 31.18,
        image: "https://ae01.alicdn.com/kf/Sc518a5ccb9344ada986f7f37aa689fe0f/Men-Jackets-Pilot-Bomber-Jacket-Fashion-Baseball-Streetwear-Coats-Slim-Fit-Coats-Brand-Men-s-Spring.jpg_Q90.jpg",
        title: "Men Jackets Pilot Bomber Jacket Fashion Baseball Streetwear Coats Slim Fit Coats Brand Men's Spring Casual Windbreaker Clothing",
        size:'L',
        color:'blue',
        brand: null,
        processor: null,
        display: null,
        gender: null,
        style: null,
        category_id: 9,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        price: 20.40,
        image: "https://ae01.alicdn.com/kf/S1359cbe6089649788b944d44cbacdee6K/MANTLCONX-Men-s-Winter-Coats-Warm-Thick-Fleece-Parka-Men-s-Jackets-and-Coats-Windbreak-Parka.jpg_Q90.jpg",
        title: "MANTLCONX Men's Winter Coats Warm Thick Fleece Parka Men's Jackets and Coats Windbreak Parka Men's Winter Jackets Male Coat 2022",
        size:'XL',
        color:'dark blue',
        brand: null,
        processor: null,
        display: null,
        gender: null,
        style: null,
        category_id: 9,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        price: 15.50,
        image: "https://ae01.alicdn.com/kf/S3f4fb0e1bddf454d832ffc7cf5762d1fm/2022-New-Men-s-Russia-Gazprom-Printing-Fashion-Winter-Windbreak-Thicken-Warm-Comfortable-Windproof-Hooded-Zipper.jpg_Q90.jpg",
        title: "2022 New Men's Russia Gazprom Printing Fashion Winter Windbreak Thicken Warm Comfortable Windproof Hooded Zipper Jacket Coat",
        size:'XXL',
        color:'black',
        brand: null,
        processor: null,
        display: null,
        gender: null,
        style: null,
        category_id: 9,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        price: 52.20,
        image: "https://ae01.alicdn.com/kf/Hf3a192ab5fd14e3ea4443421d38c8f95e/2021-Winter-Jacket-Men-for-DAF-Thick-Warm-Coat-Male-Windproof-Hooded-Outwear-Casual-Mountaineering-Overcoat.jpg_Q90.jpg",
        title: "2021 Winter Jacket Men for DAF Thick Warm Coat Male Windproof Hooded Outwear Casual Mountaineering Overcoat",
        size:'S',
        color:'red',
        brand: null,
        processor: null,
        display: null,
        gender: null,
        style: null,
        category_id: 9,
        createdAt: new Date(),
        updatedAt: new Date()
      },

      //SHOES

      {
        price: 15.25,
        image: "https://ae01.alicdn.com/kf/S236311deb5bb4660ae6719b9ba169f4cI/Turtleneck-American-sweater-for-men-and-women-knitwear-Winter-men-sweater-for-thick-style-trend-loose.jpg_Q90.jpg",
        title: "Turtleneck American sweater for men and women knitwear Winter men sweater for thick style trend loose slouchy outerwear sweater",
        size:'S',
        color:'multicolored',
        brand: null,
        processor: null,
        display: null,
        gender: null,
        style: null,
        category_id: 10,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        price: 41.20,
        image: "https://ae01.alicdn.com/kf/S236311deb5bb4660ae6719b9ba169f4cI/Turtleneck-American-sweater-for-men-and-women-knitwear-Winter-men-sweater-for-thick-style-trend-loose.jpg_Q90.jpg",
        title: "Turtleneck American sweater for men and women knitwear Winter men sweater for thick style trend loose slouchy outerwear sweater",
        size:'S',
        color:'multicolored',
        brand: null,
        processor: null,
        display: null,
        gender: null,
        style: null,
        category_id: 10,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        price: 44.10,
        image: "https://ae01.alicdn.com/kf/S236311deb5bb4660ae6719b9ba169f4cI/Turtleneck-American-sweater-for-men-and-women-knitwear-Winter-men-sweater-for-thick-style-trend-loose.jpg_Q90.jpg",
        title: "Turtleneck American sweater for men and women knitwear Winter men sweater for thick style trend loose slouchy outerwear sweater",
        size:'S',
        color:'multicolored',
        brand: null,
        processor: null,
        display: null,
        gender: null,
        style: null,
        category_id: 10,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        price: 63.25,
        image: "https://ae01.alicdn.com/kf/S236311deb5bb4660ae6719b9ba169f4cI/Turtleneck-American-sweater-for-men-and-women-knitwear-Winter-men-sweater-for-thick-style-trend-loose.jpg_Q90.jpg",
        title: "Turtleneck American sweater for men and women knitwear Winter men sweater for thick style trend loose slouchy outerwear sweater",
        size:'S',
        color:'multicolored',
        brand: null,
        processor: null,
        display: null,
        gender: null,
        style: null,
        category_id: 10,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        price: 12.20,
        image: "https://ae01.alicdn.com/kf/S236311deb5bb4660ae6719b9ba169f4cI/Turtleneck-American-sweater-for-men-and-women-knitwear-Winter-men-sweater-for-thick-style-trend-loose.jpg_Q90.jpg",
        title: "Turtleneck American sweater for men and women knitwear Winter men sweater for thick style trend loose slouchy outerwear sweater",
        size:'S',
        color:'multicolored',
        brand: null,
        processor: null,
        display: null,
        gender: null,
        style: null,
        category_id: 10,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        price: 15.50,
        image: "https://ae01.alicdn.com/kf/S236311deb5bb4660ae6719b9ba169f4cI/Turtleneck-American-sweater-for-men-and-women-knitwear-Winter-men-sweater-for-thick-style-trend-loose.jpg_Q90.jpg",
        title: "Turtleneck American sweater for men and women knitwear Winter men sweater for thick style trend loose slouchy outerwear sweater",
        size:'S',
        color:'multicolored',
        brand: null,
        processor: null,
        display: null,
        gender: null,
        style: null,
        category_id: 10,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        price: 20.30,
        image: "https://ae01.alicdn.com/kf/S236311deb5bb4660ae6719b9ba169f4cI/Turtleneck-American-sweater-for-men-and-women-knitwear-Winter-men-sweater-for-thick-style-trend-loose.jpg_Q90.jpg",
        title: "Turtleneck American sweater for men and women knitwear Winter men sweater for thick style trend loose slouchy outerwear sweater",
        size:'S',
        color:'multicolored',
        brand: null,
        processor: null,
        display: null,
        gender: null,
        style: null,
        category_id: 10,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        price: 26.36,
        image: "https://ae01.alicdn.com/kf/S236311deb5bb4660ae6719b9ba169f4cI/Turtleneck-American-sweater-for-men-and-women-knitwear-Winter-men-sweater-for-thick-style-trend-loose.jpg_Q90.jpg",
        title: "Turtleneck American sweater for men and women knitwear Winter men sweater for thick style trend loose slouchy outerwear sweater",
        size:'S',
        color:'multicolored',
        brand: null,
        processor: null,
        display: null,
        gender: null,
        style: null,
        category_id: 10,
        createdAt: new Date(),
        updatedAt: new Date()
      },

      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Items', null, {});
  },
};
